docker-compose-yaml: docker-compose.yml

tasks:
  post-rollout:

    - run:
        name: first cache clear
        command: cd docroot; drush -y cr all
        service: cli

    - run:
        name: database update
        command: cd docroot; drush -y updb --cache-clear=0
        service: cli

    - run:
        name: configuration import
        command: cd docroot; drush cim -y
        service: cli
    
    - run:
        name: second cache clear
        command: cd docroot; drush -y cr all
        service: cli

environments:
  master:
    cronjobs:
      - name: drush cron
        schedule: "* * * * *"
        command: drush cron
        service: cli
      - name: drush mim rss_blog
        schedule: "H * * * *" # once per Hour
        command: drush mim rss_blog
        service: cli
    routes:
      - varnish:
        - "wcetsan.wiche.edu":
            tls-acme: 'true'
            insecure: Redirect
