docker-compose-yaml: docker-compose.yml

tasks:
  post-rollout:
    
    - run:
        name: task0
        command: cd docroot; drush cim -y
        service: cli
    
    - run:
        name: task1
        command: cd docroot; drush -y updb --cache-clear=0
        service: cli
    
    - run:
        name: task2
        command: cd docroot; drush -y cr all
        service: cli
    

cronjobs:
  - name: drush cron
    schedule: "*/15 * * * *"
    command: drush cron
    service: cli

environments:
  master:
    routes:
      - varnish:
        - "wcetsan.wiche.edu":
            tls-acme: 'false'
            insecure: Redirect
