FROM uselagoon/php-7.3-cli-drupal:latest

COPY composer.json composer.lock /app/
COPY scripts /app/scripts
# COPY patches /app/patches

RUN composer install --prefer-dist --no-dev --no-suggest --optimize-autoloader --apcu-autoloader

COPY . /app

# Define where the Drupal Root is located
ENV WEBROOT=docroot
