<?php

/**
 * @file
 * Contains wcet_migrate.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function wcet_migrate_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the wcet_migrate module.
    case 'help.page.wcet_migrate':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Migrations for WCET.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_migration_plugins_alter().
 */
function wcet_migrate_migration_plugins_alter(array &$migrations) {
  $migrations['coordinators_main']['source']['path'] = drupal_get_path('module', 'wcet_migrate') . $migrations['coordinators_main']['source']['path'];
  $migrations['coordinators_second']['source']['path'] = drupal_get_path('module', 'wcet_migrate') . $migrations['coordinators_second']['source']['path'];
}
